export { default as Home } from './Home'
export { default as About } from './About'
export { default as Cards } from './Cards'
export { default as Services } from './Services'
export { default as Portfolio } from './Portfolio'
export { default as FeedbackSwiper } from './FeedbackSwiper'
export { default as Vacansy } from './Vacansy'